#!/usr/bin/env bash
# performing 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello world" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Sjallow permanent;"
sudo sed -i "s/server-name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
