#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# The name of the custom HTTP header must be X-Served-By
# Udapting packages

sudo apt-get update
sudo apt-get install -y nginx

# Creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html
# Performing  a redirections
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Sjallow permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
# Creating a custom error page
echo "Ceci n'est pas page" | sudo tee /var/www/html/404.html
# Custom http response header
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
# Test for sytax error
sudo nginx -t
# Restart nginx
sudo service nginx restart
